name: droppy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  permission_handler: ^11.3.0
  photo_manager: ^3.0.0
  photo_manager_image_provider: ^2.1.1
  transparent_image: ^2.0.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  intl: ^0.19.0
  floor: ^1.4.2
  retrofit: '>=4.0.0 <5.0.0'
  flutter_hooks: ^0.20.3
  cached_network_image: ^3.3.0
  dio: ^5.5.0+1
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  flutter_map_location_marker: ^9.0.0
  geolocator: ^12.0.0
  flutter_compass: ^0.8.0
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^10.0.1
  url_launcher: ^6.2.2
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.2
  go_router: ^14.2.0
  flutter_launcher_icons: ^0.13.1
  image_picker: ^1.1.0
  flutter_map_cache: ^1.5.0
  path_provider: ^2.1.2
  hive: ^2.2.3
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  carousel_slider: ^4.2.1
  flutter_native_splash: ^2.4.0
  lottie: ^3.1.0
  flutter_svg: ^2.0.10+1
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.5
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  webview_flutter: ^4.8.0
  crypto: ^3.0.3
  firebase_messaging: ^14.9.4
  web_socket_channel: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  build_runner: '>=2.3.0 <4.0.0'
  retrofit_generator: ^8.0.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "lib/assets/images/icon.png"
  min_sdk_version: 20
  remove_alpha_ios: true
  adaptive_icon_background: "#57C469"