// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2IP0D_deQ3McBWkY3xaSXjTA51uVmiH0',
    appId: '1:653021085122:web:4fcecd33d93aed9d51aa5b',
    messagingSenderId: '653021085122',
    projectId: 'droppy-420013',
    authDomain: 'droppy-420013.firebaseapp.com',
    storageBucket: 'droppy-420013.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFV_sd1xsHa9ubRD_u3ouT7su15w1B8B8',
    appId: '1:653021085122:android:8cc6c03e46abdc2551aa5b',
    messagingSenderId: '653021085122',
    projectId: 'droppy-420013',
    storageBucket: 'droppy-420013.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7mE9FwdWE_L_Kv28B7RpCSzbuqcriSmg',
    appId: '1:653021085122:ios:bed414360fd6964651aa5b',
    messagingSenderId: '653021085122',
    projectId: 'droppy-420013',
    storageBucket: 'droppy-420013.appspot.com',
    iosClientId: '653021085122-s8j5puvhenh1fij3b7pt9j9j6fgj1s2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.droppy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7mE9FwdWE_L_Kv28B7RpCSzbuqcriSmg',
    appId: '1:653021085122:ios:bed414360fd6964651aa5b',
    messagingSenderId: '653021085122',
    projectId: 'droppy-420013',
    storageBucket: 'droppy-420013.appspot.com',
    iosClientId: '653021085122-s8j5puvhenh1fij3b7pt9j9j6fgj1s2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.droppy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2IP0D_deQ3McBWkY3xaSXjTA51uVmiH0',
    appId: '1:653021085122:web:bae8f31bdb71b2c851aa5b',
    messagingSenderId: '653021085122',
    projectId: 'droppy-420013',
    authDomain: 'droppy-420013.firebaseapp.com',
    storageBucket: 'droppy-420013.appspot.com',
  );

}